export const PADRAO_PGR = {
  estruturaObrigatoria: [
    'Capa com vigencia (2 anos NR-01 item 1.5.4.4.6, ou 3 anos com SGSST item 1.5.4.4.6.1)',
    'Historico de Revisoes com data e descricao',
    'Identificacao da empresa (CNPJ, endereco completo, CNAE, grau de risco)',
    'CIPA - Composicao conforme NR-05',
    'Exposicao de Motivos',
    'Objetivos',
    'Responsabilidades (empregador e empregados)',
    'Consideracoes Gerais',
    'Siglas, Glossario e Legislacao Aplicada',
    'Avaliacao Qualitativa e Quantitativa dos Agentes',
    'Consideracoes sobre AEP - Analise Ergonomica Preliminar',
    'Nivel do Risco Ocupacional (matriz probabilidade x gravidade)',
    'Implantacao das Medidas de Controle (hierarquia: eliminacao, substituicao, engenharia, administrativo, EPI)',
    'Consideracoes sobre EPIs (com CA obrigatorio)',
    'Capacitacoes e Treinamentos',
    'Fluxograma da Metodologia',
    'Inventario de Riscos Ocupacionais por Setor',
    'Plano de Acao com prioridades (Imediata, Alta, Media, Baixa) e cronograma',
    'Referencias Bibliograficas',
    'Termo de Responsabilidade Tecnica',
    'Anexos',
  ],
  formatoInventarioRiscos: {
    porSetor: ['Descricao do setor', 'Cargos do setor', 'Descricao das atividades'],
    porPerigo: [
      'Grupo (Fisico/Quimico/Biologico/Ergonomico/Acidente)',
      'Perigo/Fator de Risco especifico',
      'Fundamentacao legal (NR especifica com item)',
      'Fontes ou circunstancias',
      'Meio de Propagacao',
      'Tempo de exposicao',
      'Tipo de exposicao (Permanente/Eventual/Habitual)',
      'Criterio (Quantitativo/Qualitativo)',
      'Probabilidade x Gravidade = Nivel de Risco',
      'Medicao (se aplicavel): empresa, tecnica, equipamento, valor, nivel de acao, LT',
      'Prevencao e controle (Medidas coletivas, administrativas, EPIs com CA)',
      'Acoes necessarias',
      'Orientacoes',
    ],
  },
  matrizRisco: {
    probabilidade: ['Inexistencia', 'Improvavel', 'Possivel', 'Provavel', 'Frequente'],
    gravidade: ['Inexistencia', 'Sem dano', 'Lesao leve', 'Lesao grave', 'Morte'],
    resultado: {
      'Ausencia de Risco': 'Nao exige acao',
      'Risco Baixo': 'Manter controles',
      'Risco Moderado': 'Plano de acao prazo medio',
      'Risco Alto': 'Plano de acao prazo curto',
      'Risco Critico': 'Acao imediata',
    },
  },
  referenciasNormativas: [
    'NR-01 - Disposicoes Gerais e Gerenciamento de Riscos Ocupacionais',
    'NR-05 - Comissao Interna de Prevencao de Acidentes e Assedio',
    'NR-06 - Equipamento de Protecao Individual',
    'NR-07 - Programa de Controle Medico de Saude Ocupacional',
    'NR-09 - Avaliacao e Controle das Exposicoes Ocupacionais a Agentes Fisicos, Quimicos e Biologicos',
    'NR-15 - Atividades e Operacoes Insalubres',
    'NR-17 - Ergonomia',
    'NR-26 - Sinalizacao de Seguranca',
    'NHO-01 - Avaliacao da Exposicao Ocupacional ao Ruido',
    'NHO-06 - Avaliacao da Exposicao Ocupacional ao Calor',
  ],
}

export const PADRAO_PCMSO = {
  estruturaObrigatoria: [
    'Identificacao da Empresa',
    'Vigencia (alinhada ao PGR)',
    'Historico de Revisoes',
    'Exposicao de Motivos (com referencia a Portaria 6.734/2020)',
    'Objetivos conforme NR-07 (10 diretrizes especificas a-j)',
    'Responsabilidades',
    'Glossario',
    'Consideracoes Gerais',
    'Embasamento Tecnico',
    'Atividades e Desenvolvimento',
    'Promocao da Saude do Trabalhador',
    'Orientacoes sobre Primeiros Socorros e Acidente de Trabalho',
    'Quadros de Exames por Setor',
    'Agentes de Risco',
    'Designacao de Medicos Examinadores (com CRM)',
    'Informacoes e Assinatura do Medico Responsavel',
    'Termo de Ciencia e Responsabilidade da Empresa',
    'Anexo A - Informacoes Medicas: Riscos, Efeitos a Saude e Exames',
    'Anexo B - Cronograma de Acoes do PCMSO',
  ],
  referenciaCritica: 'Portaria 6.734/2020 do Ministerio do Trabalho',
}

export const PADRAO_POLITICA_AMBIENTAL = {
  estruturaObrigatoria: [
    '1. Proposito (alinhado com ISO 14001)',
    '2. Escopo (atividades, produtos, servicos)',
    '3. Compromissos da Organizacao (3.1 Protecao do Meio Ambiente, 3.2 Atendimento a Requisitos Legais, 3.3 Melhoria Continua do SGA)',
    '4. Diretrizes Ambientais Estrategicas (GEE, eficiencia energetica, agua, ar, produtos quimicos, residuos, biodiversidade, solo, ruido ambiental)',
    '5. Integracao com o Sistema de Gestao Ambiental',
    '6. Comunicacao',
    '7. Responsabilidades (Alta Direcao)',
    '8. Revisao e Aprovacao',
  ],
  referenciasNormativas: [
    'ISO 14001:2015',
    'ISO 14004',
    'Lei 12.305/2010 PNRS',
    'CONAMA 307/2002',
    'CONAMA 358/2005',
    'CONAMA 430/2011',
  ],
}
